config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"

  resources :account_activations, only: [:edit]
  resources :bookings do
    member do
      patch :change_status
      put :change_status
      patch :recover
      put :recover
      delete :purge
      post :hook
      get :pay
    end
  end
  resources :categories
  resources :comments do
    resources :comments
  end
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :revenues do
    collection do
      get :revenue_detail
    end
  end
  resources :reviews do
    resources :comments
    resources :likes
  end
  resources :tours do
    member do
      patch :recover
      put :recover
      delete :purge
    end
  end
  resources :tour_details do
    member do
      patch :recover
      put :recover
      delete :purge
    end
    # collection do
    #   match "search" => "tour_details#search", via: [:get, :post], as: :search
    # end
  end
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks",
                                    registrations: "users/registrations",
                                    sessions: "users/sessions",
                                    passwords: "users/passwords",
                                    confirmations: "users/confirmations" }
  resources :users, only: [:index, :show, :edit, :update, :destroy]
  end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end

  def help; end

  def about; end

  def contact; end
end

app/views/static_pages/about.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".h1" %></h1>
<p>
  <%= t ".p" %>
  <%= t ".p1" %>
  <%= t ".p2" %>
</p>

app/views/static_pages/contact.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".h1" %></h1>
<p>
  <%= t ".p" %>
  <%= link_to t(".sun_contact"), href="https://sun-asterisk.vn/contact-us/" %>
</p>

app/views/static_pages/help.html.erb
<% provide :title, t(".title")%>
<h1><%= t ".h1" %></h1>
<p>
  <%= t ".p" %>
</p>

app/views/static_pages/home.html.erb
<% provide :title, t(".title") %>
<div class="center jumbotron">
  <h1><%= t ".big_title" %></h1>

  <h2>
    <%= t ".small_title" %>
  </h2>

  <% unless user_signed_in? %>
    <%= link_to t(".signupnow"), new_user_registration_path, class: "btn btn-lg btn-primary" %>
  <% end %>
</div>
<div style="margin-top: 100px;">
  <div class="home-tours">
      <h1>
        Available tours
      </h1>
      <%= link_to tour_details_path do %>
        <p> More </p>
      <% end %>
      <div class="clearfix"></div>
  </div>
  <div class="col">
    <% load_top_tours.each do |tour_detail| %>
      <div class="col-md">
        <div class="thumbnail tour-card">
          <div class="row card-row">
            <div class="col-md-5 pic-section" >
              <%= image_tag tour_detail.pictures.first&.link&.url, class: "tourdetail-pic" %>
            </div>
          <div class="col-md-7">
            <div class="caption">
              <h3>
                <%= link_to tour_detail.tour.name, tour_detail %>
              </h3>
              <div class="description"><%= tour_detail.tour.description %></div>
                <ul class="list-group list-group-flush tour-info">
                  <li class="list-group-item"><%= t ".start_time" %>: <%= tour_detail.start_time %></li>
                  <li class="list-group-item"><%= t ".end_time" %>: <%= tour_detail.end_time %></li>
                  <li class="list-group-item"><%= t ".price" %>: <%= tour_detail.price %></li>
                  <li class="list-group-item"><%= tour_detail.people_number %> <%= t ".people_number" %></li>
                </ul>
            </div>
          </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>