config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"

  resources :account_activations, only: [:edit]
  resources :bookings do
    member do
      patch :change_status
      put :change_status
      patch :recover
      put :recover
      delete :purge
      post :hook
      get :pay
    end
  end
  resources :categories
  resources :comments do
    resources :comments
  end
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :revenues do
    collection do
      get :revenue_detail
    end
  end
  resources :reviews do
    resources :comments
    resources :likes
  end
  resources :tours do
    member do
      patch :recover
      put :recover
      delete :purge
    end
  end
  resources :tour_details do
    member do
      patch :recover
      put :recover
      delete :purge
    end
    # collection do
    #   match "search" => "tour_details#search", via: [:get, :post], as: :search
    # end
  end
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks",
                                    registrations: "users/registrations",
                                    sessions: "users/sessions",
                                    passwords: "users/passwords",
                                    confirmations: "users/confirmations" }
  resources :users, only: [:index, :show, :edit, :update, :destroy]
  end

app/models/tour_detail.rb
class TourDetail < ApplicationRecord
  include Pictureable
  attr_accessor :link
  belongs_to :tour
  has_many :reviews, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_one :revenue, dependent: :destroy
  has_many :pictures, as: :pictureable, dependent: :destroy,
            inverse_of: :pictureable
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :price, presence: true
  validates :people_number, presence: true
  validate :end_time_after_start_time?
  after_save :add_picture
  scope :not_deleted, ->{where("deleted_at IS NULL")}
  scope :deleted, ->{where("deleted_at IS NOT NULL")}
  scope :available, ->{where("people_number > 0")}
  scope :top3, ->{where("people_number > 0 AND deleted_at IS NULL").limit(3)}

  accepts_nested_attributes_for :pictures,
                                reject_if:
                                proc{|attributes| attributes["link"].blank?}

  def self.search term
    if term
      joins(:tour).where("tours.name LIKE ?", "%#{term}%")
    else
      includes(:tour).all
    end
  end

  def soft_delete
    update deleted_at: Time.zone.now
  end

  def recover
    update deleted_at: nil
  end

  def add_picture
    save_picture "TourDetail"
  end

  private

  def end_time_after_start_time?
    return unless end_time? && start_time?

    return unless end_time < start_time

    errors.add :end_time, "must be after start date"
  end
end

app/controllers/tour_details_controller.rb
class TourDetailsController < ApplicationController
  before_action :load_tour_detail, except: %i(index new create)
  load_and_authorize_resource

  def index
    @tour_details = if current_user&.admin?
                      if params.key?(:soft_deleted)
                        TourDetail.includes(:tour).all
                                  .paginate(page: params[:page])
                      else
                        get_existed_tour_details
                      end
                    else
                      get_available_tour_details
                    end
    search_tour
  end

  def new
    @tour_detail = TourDetail.new
  end

  def show
    if @tour = Tour.find_by(id: @tour_detail.tour_id)
      return if @category = Category.find_by(id: @tour.category_id)

      flash[:danger] = t "categories.nonexist"
    else
      flash[:danger] = t "tours.nonexist"
    end
    render :index
  end

  def create
    @tour_detail = TourDetail.new tour_detail_params
    @tour_detail.link = params[:tour_detail][:pictures_attributes][:link]
    if @tour_detail.save
      flash[:success] = t ".create_success"
      redirect_to @tour_detail
    else
      flash[:danger] = t ".create_failed"
      render :new
    end
  end

  def destroy
    if @tour_detail.soft_delete
      flash[:success] = t ".delete_success"
    else
      flash[:danger] = t ".delete_failed"
    end
    redirect_to tour_details_path
  end

  def purge
    if @tour_detail.destroy
      flash[:success] = t ".purge_success"
    else
      flash[:danger] = t ".purge_failed"
    end
    redirect_to tour_details_path
  end

  def recover
    if @tour_detail.recover
      flash[:success] = t ".recover_success"
    else
      flash[:danger] = t ".recover_failed"
    end
    redirect_to tour_details_path
  end

  def edit; end

  def update
    @tour_detail.link = params[:tour_detail][:pictures_attributes][:link]
    if @tour_detail.update tour_detail_params
      flash[:success] = t ".update_success"
      redirect_to @tour_detail
    else
      flash[:danger] = t ".update_failed"
      render :edit
    end
  end

  private

  def search_tour
    @search = TourDetail.ransack(params[:q])
    @tour_details = @search.result.includes(:tour)
                           .paginate(page: params[:page])
    return if params.key?(:q)
  end

  def tour_detail_params
    params.require(:tour_detail).permit :start_time, :end_time, :tour_id,
                                        :price, :people_number, :term
  end

  def load_tour_detail
    return if @tour_detail = TourDetail.find_by(id: params[:id])

    flash[:danger] = t "tour_details.nonexist"
    redirect_to root_path
  end

  def get_existed_tour_details
    TourDetail.includes(:tour).not_deleted
              .paginate(page: params[:page])
  end

  def get_available_tour_details
    TourDetail.includes(:tour).available
              .paginate(page: params[:page])
  end
end

app/helpers/tour_details_helper.rb
module TourDetailsHelper
  def get_reviews tour_detail_id
    Review.includes(:user, :tour_detail)
          .where(tour_detail_id: tour_detail_id)
          .paginate(page: params[:page])
  end
end

app/views/tour_details/_form.html.erb
<%= form_for @tour_detail do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.label t(".tour") %>
  <%= f.select :tour_id, options_from_collection_for_select(Tour.all, :id, "name") %>

  <%= f.label t(".start_time") %>
  <%= f.date_field :start_time, min: Date.today, class: "form-control" %>

  <%= f.label t(".end_time") %>
  <%= f.date_field :end_time, min: :start_time, class: "form-control" %>

  <%= f.label t(".price") %>
  <%= f.text_field :price, class: "form-control" %>

  <%= f.label t(".people_number") %>
  <%= f.number_field :people_number, class: "form-control" %>

  <div class="form-group">
    <div class="picture-info">
      <%= f.fields_for :pictures_attributes do |image_f| %>
        <%= image_f.hidden_field :picture_cache %>
        <%= image_f.file_field :link %>
      <% end %>
    </div>
  </div>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/tour_details/_like.html.erb
<%= link_to review_likes_path(review), method: :post, remote: true do %>
  <button type="button" class="btn btn-default">
    <span class="glyphicon glyphicon-thumbs-up" style="font-size:14px;"></span>
      Like
  </button>
<% end %>

app/views/tour_details/_like_form.html.erb
<div class="like-form" id="like_form">
  <% pre_like = review.likes.find { |like| like.user_id == current_user.id} %>
  <% if pre_like %>
    <%= render partial: "unlike", locals: {review: review} %>
  <% else %>
    <%= render partial: "like", locals: {review: review} %>
  <% end %>
</div>

app/views/tour_details/_unlike.html.erb
<% pre_like = review.likes.find { |like| like.user_id == current_user.id} %>
<%= link_to review_like_path(review, pre_like), method: :delete, remote: true do %>
  <button type="button" class="btn btn-default">
    <span class="glyphicon glyphicon-thumbs-down" style="font-size:14px"></span>
    Unlike
  </button>
<% end %>

app/views/tour_details/edit.html.erb
<% provide :title, t(".title") %>
<% provide :button_text, t(".update") %>
<h1><%= t ".h1" %> <%= @tour_detail.tour.name %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/tour_details/index.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".h1" %></h1>

<%= search_form_for @search, class: "form-inline" do |f| %>
	<div class="form-group">
    <%= f.text_field :tour_name_cont, class: "form-control", placeholder: t(".placeholder") %>
  </div>
  <div class="form-group">
    <%= f.select :tour_category_id_eq, options_from_collection_for_select(Category.all, "id", "name", @search.tour_category_id_eq),
                                       {include_blank: t(".category_filter")} %>
  </div>
  <%= f.submit t(".search"), class: "btn btn-default search-btn" %>
<% end %>

<% if can? :new, @tour_detail %>
  <div class="add_btn">
    <%= link_to new_tour_detail_path, class: "btn btn-sm btn-primary" do %>
      <span class="glyphicon glyphicon-plus"></span> <%= t ".add" %>
    <% end %>
    <% if params.has_key?(:soft_deleted) %>
      <%= link_to tour_details_path, class: "btn btn-sm btn-primary" do %>
        <%= t "tours.excludes_deleted" %>
      <% end %>
    <% else %>
      <%= link_to tour_details_path(soft_deleted: true), class: "btn btn-sm btn-warning" do %>
        <%= t "tours.includes_deleted" %>
      <% end %>
    <% end %>
  </div>
<% end %>

<div class="col">
  <% @tour_details.each do |tour_detail| %>
    <div class="col-md">
      <div class="thumbnail tour-card">
        <div class="row card-row">
        <div class="col-md-5 pic-section" >
          <%= image_tag tour_detail.pictures.first&.link&.url, class: "tourdetail-pic" %>
        </div>
        <div class="col-md-7">
          <div class="caption">
            <h3>
              <%= link_to tour_detail.tour.name, tour_detail %>
            </h3>
            <div class="description"><%= tour_detail.tour.description %></div>
              <ul class="list-group list-group-flush tour-info">
                <li class="list-group-item"><%= t ".start_time" %>: <%= tour_detail.start_time %></li>
                <li class="list-group-item"><%= t ".end_time" %>: <%= tour_detail.end_time %></li>
                <li class="list-group-item"><%= t ".price" %>: <%= tour_detail.price %></li>
                <li class="list-group-item"><%= tour_detail.people_number %> <%= t ".people_number" %></li>
              </ul>
              <% if can? [:edit, :destroy, :purge, :recover], tour_detail %>
                <div class="btn-group">
                  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <%= t "tours.index.actions" %> <span class="caret"></span>
                  </button>
                  <ul class="dropdown-menu">
                    <li>
                      <%= link_to edit_tour_detail_path(tour_detail) do %>
                        <span class="glyphicon glyphicon-pencil"></span>
                        <%= t "tours.index.edit" %>
                      <% end %>
                    </li>
                    <li>
                      <%= link_to purge_tour_detail_path(tour_detail), method: :delete,
                                        data: { confirm: t(".confirm") } do %>
                        <span class="glyphicon glyphicon-remove"></span>
                        <%= t "tours.index.purge" %>
                      <% end %>
                    </li>
                    <li>
                      <%= link_to recover_tour_detail_path(tour_detail), method: :put do %>
                        <span class="glyphicon glyphicon-repeat"></span>
                        <%= t "tours.index.recover" %>
                      <% end %>
                    </li>
                    <li>
                      <%= link_to tour_detail, method: :delete,
                                        data: { confirm: t(".confirm") } do %>
                        <span class="glyphicon glyphicon-trash"></span>
                        <%= t "tours.index.delete" %>
                      <% end %>
                    </li>
                  </ul>
                </div>
              <% end %>
          </div>
        </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= will_paginate @tour_details %>

app/views/tour_details/new.html.erb
<% provide :title, t(".title") %>
<% provide :button_text, t(".create") %>
<h1><%= t ".h1" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/tour_details/show.html.erb
<% provide :title, @tour.name %>
<div class="row">
  <aside class="col-md">
    <section class="user_info">
      <h1 class = "tour-name">
        <%= @tour.name %> | <%= @category.name %>
      </h1>
      <div class="review-picture">
        <%= render partial: "pictures/picture", locals: {pictureable: @tour_detail} %>
      </div>
      <p class = "tourdetail_label_1" ><%= t ".description" %></p>
      <p class = "tour-description">
        <%= @tour.description %>
      </p>
      <p class = "tourdetail_label_1" ><%= t ".info" %></p>
      <div class = "col-md-6">
        <p class = "tourdetail_label" ><%= t ".start_time" %></p>
        <p>
          <%= @tour_detail.start_time %>
        </p>
        <p class = "tourdetail_label" ><%= t ".end_time" %></p>
        <p>
          <%= @tour_detail.end_time %>
        </p>
        <p class = "tourdetail_label" ><%= t ".price" %></p>
        <p>
          <%= @tour_detail.price %>
        </p>
        <p class = "tourdetail_label" ><%= t ".people_number" %></p>
        <p>
          <%= @tour_detail.people_number %>
        </p>
      </div>
      <div class = "col-md-6">
        <div class= "btn-actions">
          <% if user_signed_in? %>
            <div class="tour-btn">
              <% if @tour_detail.people_number != Settings.out_of_slots%>
                <p class = "booking-text"><%= @tour_detail.price %> per person</p>
                <%= link_to t(".book"), new_booking_path(tour_detail: @tour_detail.id), data: { modal: true }, class: "btn btn-danger btn-lg booking-btn" %>
                <ul class= "text-box">
                  <li> <%= t ".e-ticket" %> </li>
                  <li> <%= t ".ezcancel" %> </li>
                  <li> <%= t ".fastconfirm" %> </li>
                </ul>
              <% else %>
                <p><%= t ".out_slots" %></p>
              <% end %>
            </div>
          <% else %>
            <h2> <%= t ".bookhint" %> </h2>
          <% end %>
        </div>
      </div>
    </section>
  </aside>
</div>

<div class="row">
  <h2 class="reviews"><%= t ".title"%></h2>
  <% if user_signed_in? %>
    <%= link_to t(".review"), new_review_path(tour_detail: @tour_detail.id, user: current_user.id), data: { modal: true }, class: "btn btn-info review-btn" %>
  <% end %>
  <% unless get_reviews(@tour_detail.id).empty? %>
    <% get_reviews(@tour_detail.id).each do |review| %>
      <div class="col-md review-section">
        <div class="review-btn-section">
        <% if user_signed_in? %>
          <% if can? :destroy, review %>
            <div class="review-delete-btn">
              <%= link_to review, method: :delete,
                                          data: { confirm: t("reviews.index.confirm") }, class: "btn btn-sm btn-light" do %>
                  <span class="glyphicon glyphicon-remove"></span>
              <% end %>
            </div>
          <% end %>
        <% end %>
        </div>
        <div class="row">
          <div class="col-md-3">
            <div class="rating-back"> <p class="rating"> <%= review.rating %><%= t ".max_rating" %> </p> </div>
            <p class="review-user"> <%= review.user.name %> </p>
            <h2> <%= review.created_at.strftime("%d %b %Y") %> </h2>
          </div>
          <div class="col-md-9">
            <div class="review-content"> <%= review.content %> </div>
            <div class="review-picture">
              <%= render partial: "pictures/picture", locals: {pictureable: review} %>
            </div>
          </div>
        </div>
        <p class="like" id="likes" ><%= review.likes.count %> <%= (review.likes.count) == Settings.like_count ? t(".like") : t(".likes") %></p>
        <% if user_signed_in? %>
          <%= render partial: "like_form", locals: {review: review} %>
        <% end %>
        <button type="button" class="btn btn-default cmt">
          <span class="glyphicon glyphicon-comment"></span>
          Comment
        </button>

        <div class="comment-section">  
          <%= render partial: "comments/comment", locals: {commentable: review} %>
          <% if user_signed_in? %>
            <%= render partial: "comments/form", locals: {commentable: review} %>
          <% end %>
        </div>
      </div>
    <% end %>
  <% else %>
      <div class="no-reviews">
          <%= t ".no_reviews" %>
      </div>
  <% end %>
</div>