config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"

  resources :account_activations, only: [:edit]
  resources :bookings do
    member do
      patch :change_status
      put :change_status
      patch :recover
      put :recover
      delete :purge
      post :hook
      get :pay
    end
  end
  resources :categories
  resources :comments do
    resources :comments
  end
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :revenues do
    collection do
      get :revenue_detail
    end
  end
  resources :reviews do
    resources :comments
    resources :likes
  end
  resources :tours do
    member do
      patch :recover
      put :recover
      delete :purge
    end
  end
  resources :tour_details do
    member do
      patch :recover
      put :recover
      delete :purge
    end
    # collection do
    #   match "search" => "tour_details#search", via: [:get, :post], as: :search
    # end
  end
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks",
                                    registrations: "users/registrations",
                                    sessions: "users/sessions",
                                    passwords: "users/passwords",
                                    confirmations: "users/confirmations" }
  resources :users, only: [:index, :show, :edit, :update, :destroy]
  end

app/models/tour.rb
class Tour < ApplicationRecord
  belongs_to :category
  has_many :tour_details, dependent: :destroy
  validates :name, presence: true, uniqueness: {case_sensitive: false}
  validates :description, presence: true
  scope :not_deleted, ->{where("deleted_at IS NULL")}
  scope :deleted, ->{where("deleted_at IS NOT NULL")}

  def soft_delete
    update deleted_at: Time.zone.now
  end

  def recover
    update deleted_at: nil
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :load_tour, except: %i(index new create)
  load_and_authorize_resource

  def index
    @tours = if params.key?(:soft_deleted)
               Tour.includes(:category).all
                   .paginate(page: params[:page])
             else
               Tour.includes(:category).not_deleted
                   .paginate(page: params[:page])
             end
  end

  def show
    return if @category = Category.find_by(id: @tour.category_id)

    flash[:danger] = t "categories.nonexist"
    redirect_to root_path
  end

  def new
    @tour = Tour.new
  end

  def create
    @tour = Tour.new tour_params
    if @tour.save
      flash[:success] = t ".add_success"
      redirect_to @tour
    else
      flash[:danger] = t ".add_failed"
      render :new
    end
  end

  def destroy
    if @tour.soft_delete
      flash[:success] = t ".delete_success"
    else
      flash[:danger] = t ".delete_failed"
    end
    redirect_to tours_path
  end

  def purge
    if @tour.destroy
      flash[:success] = t ".purge_success"
    else
      flash[:danger] = t ".purge_failed"
    end
    redirect_to tours_path
  end

  def recover
    if @tour.recover
      flash[:success] = t ".recover_success"
    else
      flash[:danger] = t ".recover_failed"
    end
    redirect_to tours_path
  end

  def edit; end

  def update
    if @tour.update tour_params
      flash[:success] = t ".update_success"
      redirect_to @tour
    else
      flash[:danger] = t ".update_failed"
      render :edit
    end
  end

  private

  def tour_params
    params.require(:tour).permit(:name, :description, :category_id)
  end

  def load_tour
    return if @tour = Tour.find_by(id: params[:id])

    flash[:danger] = t "tours.nonexist"
    redirect_to root_path
  end
end

app/views/tours/_form.html.erb
<%= form_for @tour do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.label t(".name") %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label t(".description") %>
  <%= f.text_area :description, class: "form-control" %>

  <%= f.label t(".category") %>
  <%= f.select :category_id, options_from_collection_for_select(Category.all, :id, "name") %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/tours/edit.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".h1" %> <%= @tour.name %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @tour do |f| %>

      <%= f.label t(".name") %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label t(".description") %>
      <%= f.text_area :description, class: "form-control" %>

      <%= f.label t(".category") %>
      <%= f.select :category_id, options_from_collection_for_select(Category.all, :id, "name") %>

      <%= f.submit t(".update"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/tours/index.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".h1" %></h1>

<div class="add_btn">
  <%= link_to new_tour_url, class: "btn btn-sm btn-primary" do %>
    <span class="glyphicon glyphicon-plus"></span> <%= t ".add" %>
  <% end %>
  <% if params.has_key?(:soft_deleted) %>
    <%= link_to tours_path, class: "btn btn-sm btn-primary" do %>
      <%= t ".excludes_deleted" %>
    <% end %>
  <% else %>
    <%= link_to tours_path(soft_deleted: true), class: "btn btn-sm btn-warning" do %>
      <%= t ".includes_deleted" %>
    <% end %>
  <% end %>
</div>

<table>
  <thead>
    <th> <%= t ".name" %> </th>
    <th> <%= t ".cat_name" %> </th>
    <th> <%= t ".created_at" %> </th>
    <th> <%= t ".updated_at" %> </th>
    <th> <%= t ".operations" %> </th>
  </thead>
    <tbody>
      <% @tours.each do |tour| %>
        <tr>
          <td> <%= link_to tour.name, tour %> </td>
          <td> <%= tour.category.name %> </td>
          <td> <%= tour.created_at %> </td>
          <td> <%= tour.updated_at %> </td>
          <td>
            <div class="btn-group">
              <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= t ".actions" %> <span class="caret"></span>
              </button>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to edit_tour_path(tour) do %>
                    <span class="glyphicon glyphicon-pencil"></span>
                    <%= t ".edit" %>
                  <% end %>
                </li>
                <li>
                  <%= link_to purge_tour_path(tour), method: :delete,
                                     data: { confirm: t(".confirm") } do %>
                    <span class="glyphicon glyphicon-remove"></span>
                    <%= t ".purge" %>
                  <% end %>
                </li>
                <li>
                  <%= link_to recover_tour_path(tour), method: :put do %>
                    <span class="glyphicon glyphicon-repeat"></span>
                    <%= t ".recover" %>
                  <% end %>
                </li>
                <li>
                  <%= link_to tour, method: :delete,
                                     data: { confirm: t(".confirm") } do %>
                    <span class="glyphicon glyphicon-trash"></span>
                    <%= t ".delete" %>
                  <% end %>
                </li>
              </ul>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
</table>
<%= will_paginate @tours%>

app/views/tours/new.html.erb
<% provide :title, t(".title") %>
<% provide :button_text, t(".create") %>
<h1><%= t ".h1" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/tours/show.html.erb
<% provide :title, @tour.name %>
<div class="row">
  <aside class="col-md">
    <section class="user_info">
      <h1 class = "tour-name">
        <%= @tour.name %> | <%= @category.name %>
      </h1>
      <p class = "tour-description">
        <%= @tour.description %>
      </p>
    </section>
  </aside>
</div>