config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"

  resources :account_activations, only: [:edit]
  resources :bookings do
    member do
      patch :change_status
      put :change_status
      patch :recover
      put :recover
      delete :purge
      post :hook
      get :pay
    end
  end
  resources :categories
  resources :comments do
    resources :comments
  end
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :revenues do
    collection do
      get :revenue_detail
    end
  end
  resources :reviews do
    resources :comments
    resources :likes
  end
  resources :tours do
    member do
      patch :recover
      put :recover
      delete :purge
    end
  end
  resources :tour_details do
    member do
      patch :recover
      put :recover
      delete :purge
    end
    # collection do
    #   match "search" => "tour_details#search", via: [:get, :post], as: :search
    # end
  end
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks",
                                    registrations: "users/registrations",
                                    sessions: "users/sessions",
                                    passwords: "users/passwords",
                                    confirmations: "users/confirmations" }
  resources :users, only: [:index, :show, :edit, :update, :destroy]
  end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tours, dependent: :destroy
  validates :name, presence: true, uniqueness: {case_sensitive: false}
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :load_category, except: %i(index new create)
  authorize_resource

  def index
    @search = Category.ransack(params[:q])
    @categories = @search.result
                         .paginate(page: params[:page])
    return if params.key?(:q)

    @categories = Category.all.paginate(page: params[:page])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new cat_params
    if @category.save
      flash[:success] = t ".add_success"
      redirect_to categories_path
    else
      render :new
    end
  end

  def show; end

  def destroy
    if @category.destroy
      flash[:success] = t ".delete_success"
    else
      flash[:danger] = t ".delete_failed"
    end
    redirect_to categories_path
  end

  def edit; end

  def update
    if @category.update cat_params
      flash[:success] = t ".update_success"
      redirect_to @category
    else
      flash[:danger] = t ".update_failed"
      render :edit
    end
  end

  private

  def cat_params
    params.require(:category).permit(:name)
  end

  def load_category
    @category = Category.find_by id: params[:id]
    return if @category

    flash[:danger] = t "categories.nonexist"
    redirect_to root_path
  end
end

app/views/categories/_admin.html.erb
<%= render partial: "search" %>
<table>
  <thead>
    <th> <%= sort_link(@search, :cat_name, t(".cat_name")) %> </th>
    <th> <%= t ".created_at" %> </th>
    <th> <%= t ".updated_at" %> </th>
    <th> <%= t ".operations" %> </th>
  </thead>
    <tbody>
      <% categories.each do |category| %>
        <tr>
          <td> <%= category.name %> </td>
          <td> <%= category.created_at %> </td>
          <td> <%= category.updated_at %> </td>
          <td>
          <% if current_user&.role == "admin"%>
            <%= link_to edit_category_path(category), class: "btn btn-sm btn-warning" do %>
              <span class="glyphicon glyphicon-pencil"></span>
            <% end %>
            <%= link_to category, method: :delete,
                                     data: { confirm: t(".confirm") }, class: "btn btn-sm btn-danger" do %>
              <span class="glyphicon glyphicon-trash"></span>
            <% end %>
          <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
</table>
<%= will_paginate categories%>

app/views/categories/_search.html.erb
<%= search_form_for @search, class: "form-inline" do |f| %>
	<div class="form-group">
    <%= f.text_field :name_cont, class: "form-control", placeholder: t("categories.admin.cat_name") %><br>
  </div>
  <%= f.submit t("categories.admin.search"), class: "btn btn-default search-btn" %>
<% end %>

app/views/categories/_user.html.erb
<%= render partial: "search" %>
<div class="row">
  <% categories.each do |category| %>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <div class="caption">
          <h3><%= category.name %></h3>
          <p><%= link_to t(".seemore"), category, class: "btn btn-info" %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>
<%= will_paginate categories%>

app/views/categories/edit.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".h1" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @category do |f| %>
      <%= render "shared/error_messages", object: f.object %>

      <%= f.label t(".name") %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.submit t(".update"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/categories/index.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".h1" %></h1>

<% if can? :new, @category %>
  <div class="add_btn">
    <%= link_to new_category_url, class: "btn btn-sm btn-primary" do %>
      <span class="glyphicon glyphicon-plus"></span> <%= t ".add" %>
    <% end %>
  </div>
<% end %>

<% if current_user&.admin? %>
  <%= render partial: "admin", locals: {categories: @categories} %>
<% else %>
  <%= render partial: "user", locals: {categories: @categories} %>
<% end %>

app/views/categories/new.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".h1" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @category do |f| %>
      <%= render "shared/error_messages", object: f.object %>

      <%= f.label t(".name") %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.submit t(".add"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/categories/show.html.erb
<% provide :title, @category.name %>
<div class="row">
  <aside class="col-md">
    <section class="user_info">
      <h1 class = "tour-name">
        <%= @category.name %>
      </h1>
    </section>
      <h3>Tours: </h3>
      <div class="col">
        <% @category.tours.each do |tour| %>
          <% if tour.tour_details.not_deleted.empty?  %>
            <div class="no-reviews">
              <%= t ".no_tours" %>
            </div>
          <% else %>
            <% tour.tour_details.not_deleted.each do |tour_detail| %>
              <div class="col-md">
                <div class="thumbnail tour-card">
                  <div class="row card-row">
                    <div class="col-md-5 pic-section" >
                      <%= image_tag tour_detail.pictures.first&.link&.url, class: "tourdetail-pic" %>
                    </div>
                <div class="col-md-7">
                  <div class="caption">
                    <h3> <%= link_to tour_detail.tour.name, tour_detail %> </h3>
                    <div class="description"><%= tour_detail.tour.description %></div>
                      <ul class="list-group list-group-flush tour-info">
                        <li class="list-group-item"><%= t ".start_time" %>: <%= tour_detail.start_time %></li>
                        <li class="list-group-item"><%= t ".end_time" %>: <%= tour_detail.end_time %></li>
                        <li class="list-group-item"><%= t ".price" %>: <%= tour_detail.price %></li>
                        <li class="list-group-item"><%= tour_detail.people_number %> <%= t ".people_number" %></li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
  </aside>
</div>